[package]
name = "theseus"
version = "0.1.0"
compiler = "0.13.1"
entrypoint = "src/lib.typ"
authors = [
    "Leander Herter <https://github.com/leanderhert>",
    "Rasmus Buurman <https://github.com/rabuu>",
]
repository = "https://github.com/leanderhert/Theseus"
license = "MIT"
description = "A template for a university thesis or academic paper."
categories = ["layout", "report"]
keywords = ["thesis", "paper", "university", "seminar-paper"]

[template]
path = "template"
entrypoint = "main.typ"
